"""Initial migration

Revision ID: 592de19757ea
Revises:
Create Date: 2025-11-05 13:52:47.426109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db


# revision identifiers, used by Alembic.
revision: str = '592de19757ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('map', sa.Enum('eu_classic', 'stalker', 'korea', 'ops_ass', 'sradtarctica', name='gamemap', native_enum=False), nullable=False),
    sa.Column('roll_values', sa.String(length=100), nullable=False),
    sa.Column('use_cooldown', sa.Boolean(), nullable=False),
    sa.Column('cooldown', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_id'))
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('industrial', sa.Integer(), nullable=False),
    sa.Column('military', sa.Integer(), nullable=False),
    sa.Column('economic', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_country_game_id_game_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_id')),
    sa.UniqueConstraint('game_id', 'color', name=op.f('uq_country_game_id_color')),
    sa.UniqueConstraint('game_id', 'name', name=op.f('uq_country_game_id_name'))
    )
    op.create_table('last_roll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', db.datetime_utc.DatetimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_last_roll_game_id_game_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_last_roll_id')),
    sa.UniqueConstraint('game_id', 'user_id', name=op.f('uq_last_roll_game_id_user_id'))
    )
    op.create_table('tile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_tile_game_id_game_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['country.id'], name=op.f('fk_tile_owner_id_country_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tile_id')),
    sa.UniqueConstraint('game_id', 'code', name=op.f('uq_tile_game_id_code'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tile')
    op.drop_table('last_roll')
    op.drop_table('country')
    op.drop_table('game')
    # ### end Alembic commands ###
